# Generated by Django 4.2.6 on 2023-11-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.CharField(max_length=255, verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Мои скилы',
                'verbose_name_plural': 'Мой скил',
            },
        ),
    ]
