# Generated by Django 4.2.6 on 2023-11-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, verbose_name='Год')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'М',
            },
        ),
    ]
