# Generated by Django 4.2.6 on 2023-11-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
