# Generated by Django 4.2.6 on 2023-11-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_education_alter_experience_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EDUCATION',
        ),
    ]
